drop table DEMO.MEMBER;

CREATE TABLE DEMO.MEMBER ( POLICYNUM CHAR(8), POLICYTYPE CHAR(4) NOT NULL, FIRSTNAME CHAR(16) NOT NULL, LASTNAME CHAR(16) NOT NULL, STREETNUM CHAR(4) NOT NULL, STREETNAME CHAR(20) NOT NULL, CITY CHAR(20) NOT NULL, PCODE CHAR(4) NOT NULL, AGE CHAR(3) NOT NULL );

commit;